[gravity]
domain = "gravity"
host = "0.0.0.0:32803"

[subscriber]
subscriber_id = "postgres_transmitter"
subscriber_name = "Postgres Transmitter"
state_store = "./statestore"
worker_count = 4
verbose = true
pipeline_start = 0
pipeline_end = -1

# Authentication
appID = "anonymous"
accessKey = ""

[initial_load]
enabled = true
omitted_count = 100000

[rules]
subscription = "./settings/subscriptions.json"

[database]
host = "0.0.0.0"
port = 32768
secure = false
username = "postgres"
password = "1qazXSW@"
dbname = "gravity"
