[gravity]
domain = "gravity"
host = "0.0.0.0:32803"

[subscriber]
subscriberID = "postgres_transmitter"
subscriberName = "Postgres Transmitter"
stateStore = "./statestore"
workerCount = 4
verbose = true
pipelineStart = 0
pipelineEnd = -1

# Authentication
appID = "anonymous"
accessKey = ""

[initialLoad]
enabled = true
omittedCount = 100000

[rules]
subscription = "./settings/subscriptions.json"

[database]
host = "0.0.0.0"
port = 32768
secure = false
username = "postgres"
password = "1qazXSW@"
dbname = "gravity"
